### ISSUE TITLE
How do you generate the color theme for your first example?

### ISSUE THREAD

**Issue by whitewolf92** [Papercloud/flattened_active_admin#5]
Do I need to write the custom css the achieve the same color theme as your first example?

**Comment by RustComet** [comment]
@seraphimlord 

first:

```
rails g flattened_active_admin:variables
```

Then add

```
@import "flattened_active_admin/variables";
```

To the top of `active_admin.css`. This will generate a `_variables.scss` file for you where you can edit all your colors etc. 

The examples did have a bit of custom CSS thrown into them, but mostly it's just changing the variables

**Comment by whitewolf92** [comment]
Thanks. I was thinking of stealing your first example css from you. :o

Anyway, great work on it. Its the best active admin theme modifier out there right now.
